#!/bin/bash

#get the option to operate 
read -p " 2-PULL 1-PUSH 3-BASH-FILE" service

if [ $service == 1 ]
    then
        git add .

        git commit -m"done"

         git push

elif [ $service == 2 ]
    then
        git pull 

elif [ $service == 3 ]
    then
        read -p "File Name " file
        touch $file
        echo " #!/bin/bash " >> $file 
        chmod +x $file
        nano $file
        echo "you are good to go"
else
echo "please enter something in between 1-3"
fi